
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:
  password:

development:
  <<: *default
  database: tallalchat_development
  host: localhost

test:
  <<: *default
  database: tallalchat_test
  host: localhost
production:
  <<: *default
  database: tallalchat_production
  url: <%= ENV['DATABASE_URL'] %>
